"""add start_time end_time to assignments

Revision ID: 07280af95f05
Revises: 5e727114b050
Create Date: 2026-09-29 02:10:00.384547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07280af95f05'
down_revision: Union[str, Sequence[str], None] = '5e727114b050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('end_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'end_time')
    op.drop_column('assignments', 'start_time')
    # ### end Alembic commands ###
