"""add external integration ids to employee

Revision ID: 0a22ad7aaaba
Revises: 7cb4d0055897
Create Date: 2026-03-23 18:51:58.915437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a22ad7aaaba'
down_revision: Union[str, Sequence[str], None] = '7cb4d0055897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('yalam_id', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('mishmarot_id', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('shiftorg_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_employees_mishmarot_id'), 'employees', ['mishmarot_id'], unique=True)
    op.create_index(op.f('ix_employees_shiftorg_id'), 'employees', ['shiftorg_id'], unique=True)
    op.create_index(op.f('ix_employees_yalam_id'), 'employees', ['yalam_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_yalam_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_shiftorg_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_mishmarot_id'), table_name='employees')
    op.drop_column('employees', 'shiftorg_id')
    op.drop_column('employees', 'mishmarot_id')
    op.drop_column('employees', 'yalam_id')
    # ### end Alembic commands ###
