"""add target_shifts to employee_settings

Revision ID: 7cb4d0055897
Revises: 
Create Date: 2026-03-20 09:05:48.739540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cb4d0055897'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assignments', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assignments', 'shift_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assignments', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_foreign_key(None, 'assignments', 'shift_definitions', ['shift_id'], ['id'])
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('employee_settings', sa.Column('target_shifts', sa.Integer(), nullable=True))
    op.alter_column('employee_settings', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employee_settings', 'min_shifts_per_week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employee_settings', 'max_shifts_per_week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('employees', 'history_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'worked_last_fri_night',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('employees', 'worked_last_sat_noon',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('employees', 'worked_last_sat_night',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('location_weights', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_weights', 'target_shifts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_weights', 'rest_gap',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_weights', 'max_nights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_weights', 'max_mornings',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_weights', 'max_evenings',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_weights', 'min_nights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_weights', 'min_mornings',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_weights', 'min_evenings',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_weights', 'consecutive_nights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('locations', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('locations', 'cycle_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('locations', 'shifts_per_day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'EMPLOYEE', name='roleenum'),
               nullable=False)
    op.alter_column('weekly_constraints', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('weekly_constraints', 'shift_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('weekly_constraints', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('weekly_constraints', 'constraint_type',
                existing_type=sa.VARCHAR(),
                type_=sa.Enum('CANNOT_WORK', 'MUST_WORK', 'PREFER_NOT', 'PREFER_TO', name='constrainttype'),
                postgresql_using='constraint_type::constrainttype',
                nullable=False)
    op.create_foreign_key(None, 'weekly_constraints', 'shift_definitions', ['shift_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weekly_constraints', type_='foreignkey')
    op.alter_column('weekly_constraints', 'constraint_type',
               existing_type=sa.Enum('CANNOT_WORK', 'MUST_WORK', 'PREFER_NOT', 'PREFER_TO', name='constrainttype'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('weekly_constraints', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('weekly_constraints', 'shift_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('weekly_constraints', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'EMPLOYEE', name='roleenum'),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('locations', 'shifts_per_day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('locations', 'cycle_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('locations', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_weights', 'consecutive_nights',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_weights', 'min_evenings',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_weights', 'min_mornings',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_weights', 'min_nights',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_weights', 'max_evenings',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_weights', 'max_mornings',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_weights', 'max_nights',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_weights', 'rest_gap',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_weights', 'target_shifts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location_weights', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'worked_last_sat_night',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('employees', 'worked_last_sat_noon',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('employees', 'worked_last_fri_night',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('employees', 'history_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('employees', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employee_settings', 'max_shifts_per_week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employee_settings', 'min_shifts_per_week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employee_settings', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('employee_settings', 'target_shifts')
    op.alter_column('clients', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.alter_column('assignments', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('assignments', 'shift_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assignments', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assignments', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
