"""add_email_to_user

Revision ID: 7f782dd44630
Revises: abe650705d4b
Create Date: 2026-03-29 23:40:17.634927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f782dd44630'
down_revision: Union[str, Sequence[str], None] = 'abe650705d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column allowing NULL values initially
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))

    # 2. Populate existing rows with a placeholder email based on their ID
    # This prevents the NOT NULL violation and keeps the email unique
    op.execute("UPDATE users SET email = 'temp_user_' || id || '@example.com' WHERE email IS NULL")

    # 3. Alter the column to enforce NOT NULL
    op.alter_column('users', 'email', existing_type=sa.String(), nullable=False)

    # 4. Create the unique index for fast lookups and constraint
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_constraints', sa.Column('source', postgresql.ENUM('yalam', 'mishmarot', 'shiftorg', name='constraintsource'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
