"""add_weekly_notes_table

Revision ID: 88f585145327
Revises: fc364f5d5cf5
Create Date: 2026-09-14 09:05:45.488708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f585145327'
down_revision: Union[str, Sequence[str], None] = 'fc364f5d5cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'week_start_date', name='uix_employee_week')
    )
    op.create_index(op.f('ix_weekly_notes_id'), 'weekly_notes', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_notes_week_start_date'), 'weekly_notes', ['week_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_notes_week_start_date'), table_name='weekly_notes')
    op.drop_index(op.f('ix_weekly_notes_id'), table_name='weekly_notes')
    op.drop_table('weekly_notes')
    # ### end Alembic commands ###
