"""refactor_user_and_employee_models

Revision ID: abe650705d4b
Revises: b93a92630e4c
Create Date: 2026-03-29 22:15:26.989609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abe650705d4b'
down_revision: Union[str, Sequence[str], None] = 'b93a92630e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add new columns (temporarily nullable to prevent errors on existing rows)
    op.add_column('employees', sa.Column('notes', sa.String(), nullable=True))

    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))

    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)

    # 2. Data Migration: Split existing usernames into first_name and last_name
    connection = op.get_bind()

    # Fetch all existing users
    users = connection.execute(sa.text("SELECT id, username FROM users")).fetchall()

    for user_id, username in users:
        # Split by the first space
        parts = username.split(" ", 1)
        first_name = parts[0]
        last_name = parts[1] if len(parts) > 1 else ""

        # Update the specific user with the new split names
        connection.execute(
            sa.text("UPDATE users SET first_name = :fn, last_name = :ln WHERE id = :id"),
            {"fn": first_name, "ln": last_name, "id": user_id}
        )

    # 3. Drop old columns and their indices
    op.drop_index('ix_employees_name', table_name='employees')
    op.drop_column('employees', 'name')

    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_constraints', sa.Column('source', postgresql.ENUM('yalam', 'mishmarot', 'shiftorg', name='constraintsource'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('employees', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.drop_column('employees', 'notes')
    # ### end Alembic commands ###
