"""remove historical state columns from employee

Revision ID: fc364f5d5cf5
Revises: 7f782dd44630
Create Date: 2026-04-08 18:39:09.787479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc364f5d5cf5'
down_revision: Union[str, Sequence[str], None] = '7f782dd44630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'worked_last_sat_night')
    op.drop_column('employees', 'worked_last_sat_noon')
    op.drop_column('employees', 'history_streak')
    op.drop_column('employees', 'worked_last_fri_night')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('weekly_constraints', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_constraints', sa.Column('source', postgresql.ENUM('yalam', 'mishmarot', 'shiftorg', name='constraintsource'), autoincrement=False, nullable=True))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('employees', sa.Column('worked_last_fri_night', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('history_streak', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('worked_last_sat_noon', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('worked_last_sat_night', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
